# -*- coding: utf-8 -*-
"""vtpconfig.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jN8ByQ5aslFgD7mYEV0Uzd9Wh5Atz2cV
"""

import netmiko
import sys
import time
from netmiko import ConnectHandler
ios_l2_corelayer = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.33',
    'username':'pythonauto',
    'password': 'python123',
    'secret': 'cisco'

}

ios_l2_distlayer1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.34',
    'username':'pythonauto',
    'password': 'python123',
    'secret': 'cisco'
}
# commetberers
ios_l2_distlayer2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.35',
    'username':'pythonauto',
    'password': 'python123',
    'secret': 'cisco'

}
ios_l2_accesslayer1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.36',
    'username':'pythonauto',
    'password': 'python123',
    'secret': 'cisco'
}

ios_l2_accesslayer2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.37',
    'username':'pythonauto',
    'password': 'python123',
    'secret': 'cisco'

}

ios_l2_accesslayer3 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.38',
    'username':'pythonauto',
    'password': 'python123',
    'secret': 'cisco'

}

#connecting to corelayer switch
try:
    ssh_connection = ConnectHandler(**ios_l2_corelayer)
    print("connection success\n")
    ssh_connection.enable()
    print(ssh_connection.find_prompt())
    commandos = ['vtp domain corelayerswitch.com', 'vtp password python123', 'vtp mode server', 'vtp version 2']
    outputs = ssh_connection.send_config_set(commandos)
    print(outputs)

except:
    print("login failure\n")
    sys.exit()

distribution_and_access_layer_devices = [ios_l2_accesslayer1, ios_l2_accesslayer2, ios_l2_accesslayer3, ios_l2_distlayer1, ios_l2_distlayer2]
for devices in distribution_and_access_layer_devices:
    try:
        ssh_connection = ConnectHandler(**devices)
        ssh_connection.enable()
        commands = ['vtp domain corelayerswitch.com', 'vtp password python123', 'vtp mode client', 'vtp version 2']
        output = ssh_connection.send_config_set(commands)
        print(output)
        time.sleep(3)
        print("done")

    except:
        print("connection failed to this")



ssh_connection.disconnect()